/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeshop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hunain
 */
public class Adduser extends javax.swing.JFrame {

    /**
     * Creates new form Adduser
     */
    
   MyConnection m;
   
    public Adduser() {
        initComponents();
        jpassword.setVisible(false);
         m = new MyConnection();
        
  }
    
   public Adduser(String id, String name, String depart, String phone, String salary){
       
       txtid.setText(id);
       txtname.setText(name);
       txtdesignation.setText(depart);
       txtphone.setText(phone);
       txtsalary.setText(salary);
       
       
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtdesignation = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jselect = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jpassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jdate = new com.toedter.calendar.JDateChooser();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register user");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration Staff");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 41, 297, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));

        jPanel3.setBackground(new java.awt.Color(149, 165, 166));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NAME");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 126, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Department");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 188, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SALARY");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 249, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PHONE");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 321, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SELECT");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 392, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DATE");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 464, -1, -1));
        jPanel3.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 67, 219, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel3.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 127, 219, -1));
        jPanel3.add(txtdesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 189, 219, -1));
        jPanel3.add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 250, 219, -1));
        jPanel3.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 322, 219, -1));

        jselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "RECEIPTION", "WAITER\t", "OTHER" }));
        jselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jselectActionPerformed(evt);
            }
        });
        jPanel3.add(jselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 390, 220, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("PASSWORD");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 524, -1, -1));
        jPanel3.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 210, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Engravers MT", 2, 14)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 621, -1, -1));

        jButton3.setBackground(new java.awt.Color(231, 76, 60));
        jButton3.setFont(new java.awt.Font("Engravers MT", 2, 14)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));
        jPanel3.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 180, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Rest();
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jselectActionPerformed
        // TODO add your handling code here:
         
       String str = "RECEIPTION";
      if( jselect.getSelectedItem().equals(str)){
          jpassword.setVisible(true);
      }
      else{
          jpassword.setVisible(false);
      }
      
        
    }//GEN-LAST:event_jselectActionPerformed

    
     Connection cc;
    Statement st;
    String dbt = "jdbc:sqlserver://DESKTOP-BIDQUFO:1433;databaseName=cafe;user=Hunain;password=123";
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(jdate.getDate());
        
           int id = Integer.parseInt(txtid.getText());  
           String name =  txtname.getText();
           String desig  =  txtdesignation.getText();
           int salary  =   Integer.parseInt(txtsalary.getText()); 
           int no     = Integer.parseInt(txtphone.getText());     
            String pos   =   (String) jselect.getSelectedItem();
               String pass    =   jpassword.getText();
         
         
        
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            cc = DriverManager.getConnection(dbt);
            st = cc.createStatement();
             
             
             String query = "insert into StaffRec values('" + id+ "','" + name+ "','" + desig+ "','" + salary+ "','" + no+ "','" + pos+ "','" + date+ "','" + pass+ "')";
            String trig = "create trigger trgafinsert on [dbo].[StaffRec] for insert as declare @username varchar(50) declare @password nvarchar(10) select @username=i.name from inserted iselect @password=i.pass from inserted iinsert into login1(username, pass) values(@username,@password ) go ";

              int z = st.executeUpdate(query);
             
            if (z > 0) {
                JOptionPane.showMessageDialog(this, "Submitted! Sucessfully");
                Rest();
            }
            
          String str = "RECEIPTION";
      if( jselect.getSelectedItem().equals(str)){
           st.executeUpdate(trig);
      }
             
             
             
         }
         catch(Exception e)
         {
             System.out.println(e);
             
         }
         
         
         
         
         
         
         
         
         
         
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    
  
    void updatestaff(String values){
        AdminPanel ap = new AdminPanel();
         int row = ap.jTablestaff.getSelectedRow();
        //String values = ap.jTablestaff.getModel().getValueAt(row, 0).toString();
         try{
       String query = " UPDATE StaffRec SET name= ?, depart= ?, salary = ?  WHERE  id = '"+values;
           
           ResultSet rs  = m.st.executeQuery(query);
            
            while(rs.next()){
                String name = rs.getString("name");
                 String depart = rs.getString("Depart");
                  String date1 = rs.getString("joining_Date");
                  int id = rs.getInt("id");
                  float salary = rs.getFloat("salary");
                  long phone = rs.getLong("phone");
             
                  String id1 = Integer.toString(id);
                  String ph = Long.toString(phone);
                  String sal = Float.toString(salary);
                  
                  
                  
             
                  txtid.setText(id1);
                  txtname.setText(name);
                  txtdesignation.setText(depart);
                  txtphone.setText(ph);
                  txtsalary.setText(sal);
    
    
             
            
            }
   }
        catch(Exception e){
            System.out.println(e);
        }
        
        
        
        
    }
    
   
    
    
    
    
    
    
    void Rest(){
        
        txtid.setText("");
        txtname.setText("");
        txtdesignation.setText("");
        txtsalary.setText("");
        txtphone.setText("");
        jselect.setSelectedIndex(0);
        jdate.setCalendar(null);
        jpassword.setText("");
        
         }
    
  
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adduser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField jpassword;
    private javax.swing.JComboBox<String> jselect;
    public javax.swing.JTextField txtdesignation;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtname;
    public javax.swing.JTextField txtphone;
    public javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
