/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeshop;

/**
 *
 * @author Hp
 */
import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.*;
import java.util.Random;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.SimpleDateFormat;
import java.awt.Color;
import java.util.Date;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TeaShop extends javax.swing.JFrame {

    //double [] drink = new double [7];
    //double [] cake = new double[7];
    double[] drink = new double[7];
    double[] cake = new double[7];
    double[] i = new double[10];
    double[] amount = new double[5];
    double[] r = new double[5];
    String ff;

    int rofs;
    String dito;

    /**
     * Creates new form TeaShop
     */
    int x = 10;
    int y = 100;
    ImageIcon logo = new ImageIcon(getClass().getClassLoader().getResource("icon1.png"));

    public void paint(Graphics g) {

        super.paint(g);
        Graphics2D gd = (Graphics2D) g;
        gd.setColor(Color.BLACK);
        gd.setFont(new Font("Bold", Font.BOLD, 40));
        gd.drawString("WELCOME TO  CAFE", x, y);

        try {

            Thread.sleep(100);
            x += 10;

        } catch (Exception e) {
        }

        if (x > getWidth()) {
            x = 0;
        }
        repaint();

    }

    MyConnection m;

    public TeaShop() {
        initComponents();

        m = new MyConnection();
        setIconImage(logo.getImage());

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnreceipt = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tareceipt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btntax = new javax.swing.JButton();
        btnsubtotal = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();
        txttax = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        chkcoffeecake = new javax.swing.JCheckBox();
        chkredcake = new javax.swing.JCheckBox();
        chkbostoncake = new javax.swing.JCheckBox();
        chklagoscake = new javax.swing.JCheckBox();
        chkqueencake = new javax.swing.JCheckBox();
        txtcoffecake = new javax.swing.JTextField();
        txtredcake = new javax.swing.JTextField();
        txtbostoncake = new javax.swing.JTextField();
        txtlagoscake = new javax.swing.JTextField();
        txtqueencake = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        chklattle = new javax.swing.JCheckBox();
        chkicelattle = new javax.swing.JCheckBox();
        chkespresso = new javax.swing.JCheckBox();
        chkcappucino = new javax.swing.JCheckBox();
        chkicecappucino = new javax.swing.JCheckBox();
        txtlattle = new javax.swing.JTextField();
        txticelattle = new javax.swing.JTextField();
        txtespreeso = new javax.swing.JTextField();
        txtcappucino = new javax.swing.JTextField();
        txticecappucino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btncosttea = new javax.swing.JButton();
        btncostcake = new javax.swing.JButton();
        btnservice = new javax.swing.JButton();
        txtcostoftea = new javax.swing.JTextField();
        txtcostofcake = new javax.swing.JTextField();
        txtservicecharges = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtuse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setForeground(new java.awt.Color(51, 0, 51));

        jButton7.setBackground(new java.awt.Color(51, 51, 255));
        jButton7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton7.setText("Total");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 51, 153));
        jButton9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 255, 0));
        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 0, 0));
        jButton10.setText("Exit");
        jButton10.setToolTipText("Exit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnreceipt.setBackground(new java.awt.Color(247, 104, 7));
        btnreceipt.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnreceipt.setText("Receipt");
        btnreceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreceiptMouseClicked(evt);
            }
        });
        btnreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreceiptActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 4));

        tareceipt.setEditable(false);
        tareceipt.setBackground(new java.awt.Color(255, 255, 255));
        tareceipt.setColumns(20);
        tareceipt.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tareceipt.setRows(5);
        tareceipt.setText("0\n\n");
        jScrollPane2.setViewportView(tareceipt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Print Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Feed Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 0, 51));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Upload");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setText("show Record");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        btntax.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btntax.setForeground(new java.awt.Color(0, 0, 0));
        btntax.setText("Tax");

        btnsubtotal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnsubtotal.setForeground(new java.awt.Color(0, 0, 0));
        btnsubtotal.setText("Sub Total");

        btntotal.setBackground(new java.awt.Color(255, 255, 255));
        btntotal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btntotal.setForeground(new java.awt.Color(51, 51, 51));
        btntotal.setText("Total");

        txttax.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txttax.setText("0");

        txtsubtotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtsubtotal.setText("0");

        txttotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txttotal.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btntax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btntotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttotal, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(txtsubtotal)
                    .addComponent(txttax))
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 582, 540, 400));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        chkcoffeecake.setBackground(new java.awt.Color(0, 51, 51));
        chkcoffeecake.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkcoffeecake.setForeground(new java.awt.Color(255, 255, 255));
        chkcoffeecake.setText("Coffe Cake");
        chkcoffeecake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkcoffeecakeMouseClicked(evt);
            }
        });
        chkcoffeecake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcoffeecakeActionPerformed(evt);
            }
        });

        chkredcake.setBackground(new java.awt.Color(0, 51, 51));
        chkredcake.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkredcake.setForeground(new java.awt.Color(255, 255, 255));
        chkredcake.setText("Red valvet cake");
        chkredcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkredcakeMouseClicked(evt);
            }
        });
        chkredcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkredcakeActionPerformed(evt);
            }
        });

        chkbostoncake.setBackground(new java.awt.Color(0, 51, 51));
        chkbostoncake.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkbostoncake.setForeground(new java.awt.Color(255, 255, 255));
        chkbostoncake.setText("Boston cake");
        chkbostoncake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkbostoncakeMouseClicked(evt);
            }
        });
        chkbostoncake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbostoncakeActionPerformed(evt);
            }
        });

        chklagoscake.setBackground(new java.awt.Color(0, 51, 51));
        chklagoscake.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chklagoscake.setForeground(new java.awt.Color(255, 255, 255));
        chklagoscake.setText("Lagos cake");
        chklagoscake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chklagoscakeMouseClicked(evt);
            }
        });
        chklagoscake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chklagoscakeActionPerformed(evt);
            }
        });

        chkqueencake.setBackground(new java.awt.Color(0, 51, 51));
        chkqueencake.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkqueencake.setForeground(new java.awt.Color(255, 255, 255));
        chkqueencake.setText("Queen park cake");
        chkqueencake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkqueencakeMouseClicked(evt);
            }
        });
        chkqueencake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkqueencakeActionPerformed(evt);
            }
        });

        txtcoffecake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcoffecake.setText("0");
        txtcoffecake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcoffecakeActionPerformed(evt);
            }
        });

        txtredcake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtredcake.setText("0");

        txtbostoncake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbostoncake.setText("0");

        txtlagoscake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlagoscake.setText("0");

        txtqueencake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtqueencake.setText("0");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CAKES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtredcake, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkqueencake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkcoffeecake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkredcake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chklagoscake, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkbostoncake, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(txtcoffecake, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbostoncake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlagoscake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtqueencake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkcoffeecake)
                    .addComponent(txtcoffecake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkredcake)
                    .addComponent(txtredcake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkbostoncake)
                    .addComponent(txtbostoncake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chklagoscake)
                    .addComponent(txtlagoscake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkqueencake)
                    .addComponent(txtqueencake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, 450));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setForeground(new java.awt.Color(0, 0, 255));

        chklattle.setBackground(new java.awt.Color(0, 51, 51));
        chklattle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chklattle.setForeground(new java.awt.Color(255, 255, 255));
        chklattle.setText("Lattle ");
        chklattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chklattleMouseClicked(evt);
            }
        });
        chklattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chklattleActionPerformed(evt);
            }
        });

        chkicelattle.setBackground(new java.awt.Color(0, 51, 51));
        chkicelattle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkicelattle.setForeground(new java.awt.Color(255, 255, 255));
        chkicelattle.setText("Iced Lattle");
        chkicelattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkicelattleMouseClicked(evt);
            }
        });
        chkicelattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkicelattleActionPerformed(evt);
            }
        });

        chkespresso.setBackground(new java.awt.Color(0, 51, 51));
        chkespresso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkespresso.setForeground(new java.awt.Color(255, 255, 255));
        chkespresso.setText("Espreeso");
        chkespresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkespressoMouseClicked(evt);
            }
        });
        chkespresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkespressoActionPerformed(evt);
            }
        });

        chkcappucino.setBackground(new java.awt.Color(0, 51, 51));
        chkcappucino.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkcappucino.setForeground(new java.awt.Color(255, 255, 255));
        chkcappucino.setText("Cappucino");
        chkcappucino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkcappucinoMouseClicked(evt);
            }
        });
        chkcappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcappucinoActionPerformed(evt);
            }
        });

        chkicecappucino.setBackground(new java.awt.Color(0, 51, 51));
        chkicecappucino.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chkicecappucino.setForeground(new java.awt.Color(255, 255, 255));
        chkicecappucino.setText("Iced Cappucino");
        chkicecappucino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkicecappucinoMouseClicked(evt);
            }
        });
        chkicecappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkicecappucinoActionPerformed(evt);
            }
        });

        txtlattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlattle.setText("0");

        txticelattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txticelattle.setText("0");

        txtespreeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtespreeso.setText("0");

        txtcappucino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcappucino.setText("0");
        txtcappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcappucinoActionPerformed(evt);
            }
        });

        txticecappucino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txticecappucino.setText("0");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Quantity");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("COFFEE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(199, 199, 199))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(chkespresso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chklattle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkicelattle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkcappucino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(chkicecappucino))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcappucino, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txticecappucino, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtespreeso, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txticelattle, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlattle, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(127, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chklattle)
                    .addComponent(txtlattle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkespresso)
                            .addComponent(txtespreeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkicelattle)
                        .addComponent(txticelattle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtcappucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkicecappucino)
                            .addComponent(txticecappucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(chkcappucino))
                .addGap(46, 46, 46))
        );

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        btncosttea.setBackground(new java.awt.Color(0, 51, 51));
        btncosttea.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btncosttea.setForeground(new java.awt.Color(255, 255, 255));
        btncosttea.setText("Cost of Tea");

        btncostcake.setBackground(new java.awt.Color(0, 51, 51));
        btncostcake.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btncostcake.setForeground(new java.awt.Color(255, 255, 255));
        btncostcake.setText("Cost of Cake");

        btnservice.setBackground(new java.awt.Color(0, 51, 51));
        btnservice.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnservice.setForeground(new java.awt.Color(255, 255, 255));
        btnservice.setText("Service charges");

        txtcostoftea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcostoftea.setText("0");

        txtcostofcake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcostofcake.setText("0");

        txtservicecharges.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtservicecharges.setText("10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnservice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncosttea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncostcake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcostoftea)
                            .addComponent(txtcostofcake)
                            .addComponent(txtservicecharges, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncosttea, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcostoftea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncostcake, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcostofcake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtservicecharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnservice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 92, 10, 450));

        txtuse.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtuse.setForeground(new java.awt.Color(255, 255, 255));
        txtuse.setText("dd");
        jPanel7.add(txtuse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 30, 110, 20));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1900, 990));

        setBounds(0, 0, 1895, 1021);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcappucinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcappucinoActionPerformed

    private void chkespressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkespressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkespressoActionPerformed

    private void chkcappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcappucinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcappucinoActionPerformed

    private void chklattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chklattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chklattleActionPerformed
//private JFrame frame;
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        JFrame frame = new JFrame("Exit");

        if (JOptionPane.showConfirmDialog(frame, "conform if you want to exit", "Question", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {

            System.exit(0);
        }


    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        txtlattle.setText("0");
        txticelattle.setText("0");
        txtespreeso.setText("0");
        txtcappucino.setText("0");
        txticecappucino.setText("0");
        txtcoffecake.setText("0");
        txtredcake.setText("0");
        txtbostoncake.setText("0");
        txtqueencake.setText("0");
        txtlagoscake.setText("0");
        txtcostoftea.setText("0");
        txtcostofcake.setText("0");
        txtservicecharges.setText("0");
        txttax.setText("0");
        txtsubtotal.setText("0");
        txttotal.setText("0");
        tareceipt.setText("");
        chklattle.setSelected(false);
        chkbostoncake.setSelected(false);
        chkicelattle.setSelected(false);
        chkcappucino.setSelected(false);
        chkicecappucino.setSelected(false);
        chkcoffeecake.setSelected(false);
        chkespresso.setSelected(false);
        chkredcake.setSelected(false);
        chkqueencake.setSelected(false);
        chklagoscake.setSelected(false);


    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreceiptActionPerformed

    }//GEN-LAST:event_btnreceiptActionPerformed

    Date op = new Date();

    private void btnreceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreceiptMouseClicked

        SimpleDateFormat dt = new SimpleDateFormat("YYYY-MM-dd" + "HH:mm:ss");
        String td;
        dito = td = dt.format(op);

        int ref;
        rofs = ref = 365 + (int) (Math.random() * 4238);

        drink[0] = Double.parseDouble(txtlattle.getText());
        drink[1] = Double.parseDouble(txticelattle.getText());
        drink[2] = Double.parseDouble(txtespreeso.getText());
        drink[3] = Double.parseDouble(txtcappucino.getText());
        drink[4] = Double.parseDouble(txticecappucino.getText());

        cake[0] = Double.parseDouble(txtcoffecake.getText());
        cake[1] = Double.parseDouble(txtbostoncake.getText());
        cake[2] = Double.parseDouble(txtredcake.getText());
        cake[3] = Double.parseDouble(txtlagoscake.getText());
        cake[4] = Double.parseDouble(txtqueencake.getText());

        r[0] = Double.parseDouble(txttax.getText());
        r[1] = Double.parseDouble(txtsubtotal.getText());
        r[2] = Double.parseDouble(txttotal.getText());

        tareceipt.append("\t\tReceipt No :" + ref + "\t\t\nWelcome to Shaikh Cafe"
                + "\n====================================================="
                + "\n\tTEA"
                + "\nLattle\t\t" + drink[0]
                + "\nIces Lattle\t\t" + drink[1]
                + "\nEspresso\t\t" + drink[2]
                + "\nCappucino\t\t" + drink[3]
                + "\nIced Cappucino\t" + drink[4]
                + "\n======================================================="
                + "\n\tCAKES"
                + "\nCoffee cake\t\t" + cake[0]
                + "\nRed Valvet Cake\t" + cake[1]
                + "\nBoston Cake\t\t" + cake[2]
                + "\nLagos Cake\t\t" + cake[3]
                + "\nQueen Park Cake\t" + cake[4]
                + "\n========================================================"
                + "\nTax\t\t:" + r[0]
                + "\nSubTotal:\t\t" + r[1]
                + "\nTotal:\t\t" + r[2]
                + "\n" + "\nDate :" + td
                + "\n\tThank you Very Much"
                + "\n\tEnjoy Tea & Cakes");


    }//GEN-LAST:event_btnreceiptMouseClicked

    private void chklattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chklattleMouseClicked

        try {

            double clattle = Double.parseDouble(txtcostoftea.getText());
            double tlattle = Double.parseDouble(txtlattle.getText());
            double ilattle = 20.0;

            if (chklattle.isSelected()) {

                i[0] = (ilattle * tlattle) + clattle;
                String tea;
                tea = String.format("% .2f", i[0]);
                txtcostoftea.setText(tea);
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_chklattleMouseClicked

    private void chkicelattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkicelattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkicelattleActionPerformed

    private void chkicelattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkicelattleMouseClicked

        try {

            double cicelattle = Double.parseDouble(txtcostoftea.getText());
            double ticelattle = Double.parseDouble(txticelattle.getText());
            double iicelattle = 20.00;

            if (chkicelattle.isSelected()) {

                i[1] = (ticelattle * iicelattle) + cicelattle;

                String tea = String.format("%.2f", i[1]);
                txtcostoftea.setText(tea);

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "String null");

        }


    }//GEN-LAST:event_chkicelattleMouseClicked

    private void chkespressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkespressoMouseClicked

        try {

            double cespresso = Double.parseDouble(txtcostoftea.getText());
            double tespresso = Double.parseDouble(txtespreeso.getText());
            double iespresso = 20.0;

            if (chkespresso.isSelected()) {

                i[2] = (tespresso * iespresso) + cespresso;

                String tea = String.format("%.2f", i[2]);
                txtcostoftea.setText(tea);

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_chkespressoMouseClicked

    private void chkcappucinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkcappucinoMouseClicked

        try {

            double ccappucino = Double.parseDouble(txtcostoftea.getText());
            double tcappucino = Double.parseDouble(txtcappucino.getText());
            double icappucino = 20.0;

            if (chkcappucino.isSelected()) {

                i[3] = (tcappucino * icappucino) + ccappucino;

                String tea = String.format("%.2f", i[3]);
                txtcostoftea.setText(tea);

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_chkcappucinoMouseClicked

    private void chkicecappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkicecappucinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkicecappucinoActionPerformed

    private void chkicecappucinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkicecappucinoMouseClicked
        try {
            double icecappucino = Double.parseDouble(txtcostoftea.getText());
            double ticecappucino = Double.parseDouble(txticecappucino.getText());
            double iicecappucino = 20.0;

            if (chkicecappucino.isSelected()) {

                i[4] = (ticecappucino * iicecappucino) + icecappucino;

                String tea = String.format("%.2f", i[4]);
                txtcostoftea.setText(tea);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_chkicecappucinoMouseClicked

    private void chkcoffeecakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcoffeecakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcoffeecakeActionPerformed

    private void chkcoffeecakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkcoffeecakeMouseClicked

        try {
            double coffeecake = Double.parseDouble(txtcostofcake.getText());
            double tcoffeecake = Double.parseDouble(txtcoffecake.getText());
            double icoffecake = 30.0;

            if (chkcoffeecake.isSelected()) {

                i[5] = (tcoffeecake * icoffecake) + coffeecake;
                String cake = String.format("%.2f", i[5]);
                txtcostofcake.setText(cake);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_chkcoffeecakeMouseClicked

    private void chkredcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkredcakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkredcakeActionPerformed

    private void chkredcakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkredcakeMouseClicked

        try {

            double cred = Double.parseDouble(txtcostofcake.getText());
            double tred = Double.parseDouble(txtredcake.getText());
            double ired = 20.0;

            if (chkredcake.isSelected()) {

                i[6] = (tred * ired) + cred;
                String cake = String.format("%.2f", i[6]);
                txtcostofcake.setText(cake);
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_chkredcakeMouseClicked

    private void chkbostoncakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbostoncakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbostoncakeActionPerformed

    private void chkbostoncakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkbostoncakeMouseClicked
        try {
            double cboston = Double.parseDouble(txtcostofcake.getText());
            double tboston = Double.parseDouble(txtbostoncake.getText());
            double iboston = 20.0;

            if (chkbostoncake.isSelected()) {
                i[7] = (tboston * iboston) + cboston;

                String cake = String.format("%.2f", i[7]);
                txtcostofcake.setText(cake);

            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_chkbostoncakeMouseClicked

    private void chklagoscakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chklagoscakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chklagoscakeActionPerformed

    private void chklagoscakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chklagoscakeMouseClicked
        try {
            double clagos = Double.parseDouble(txtcostofcake.getText());
            double tlagos = Double.parseDouble(txtlagoscake.getText());
            double ilagos = 20.0;

            if (chklagoscake.isSelected()) {
                i[8] = (tlagos * ilagos) + clagos;
                String cake = String.format("%.2f", i[8]);
                txtcostofcake.setText(cake);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_chklagoscakeMouseClicked

    private void chkqueencakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkqueencakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkqueencakeActionPerformed

    private void chkqueencakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkqueencakeMouseClicked

        try {

            double cqueen = Double.parseDouble(txtcostofcake.getText());
            double tqueen = Double.parseDouble(txtqueencake.getText());
            double iqueen = 20.0;

            if (chkqueencake.isSelected()) {

                i[9] = (tqueen * iqueen) + cqueen;
                String cake = String.format("%.2f", i[9]);

                txtcostofcake.setText(cake);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }


    }//GEN-LAST:event_chkqueencakeMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        amount[0] = Double.parseDouble(txtcostoftea.getText());
        amount[1] = Double.parseDouble(txtcostofcake.getText());
        amount[2] = Double.parseDouble(txtservicecharges.getText());

        double ctotal = (amount[0] + amount[1] + amount[2]);

        String itax = String.format("%.2f", ctotal / 100);
        txttax.setText(itax);
        double subtotal = ctotal;
        String isubtotal = String.format("%.2f", subtotal);
        txtsubtotal.setText(isubtotal);

        double alltoal = ctotal;

        String total = String.format("%.2f", ctotal + (ctotal / 100));
        txttotal.setText(total);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtcoffecakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcoffecakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoffecakeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            tareceipt.print();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        FeedBack ff = new FeedBack();

        new FeedBack().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    class table2 extends TeaTable {

        TeaTable tt;

    }

    double amount1;

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        amount1 = Double.parseDouble(txttotal.getText());

        try {

            int z = m.st.executeUpdate("insert into shop4 values('" + rofs + "','" + amount1 + "','" + dito + "')");

            if (z > 0) {
                JOptionPane.showMessageDialog(this, "Uploded! Sucessfully");
            }

        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    TeaTable tt = new TeaTable();
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        new TeaTable().setVisible(true);


    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeaShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeaShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeaShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeaShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeaShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncostcake;
    private javax.swing.JButton btncosttea;
    public static javax.swing.JButton btnreceipt;
    private javax.swing.JButton btnservice;
    private javax.swing.JButton btnsubtotal;
    private javax.swing.JButton btntax;
    private javax.swing.JButton btntotal;
    private javax.swing.JCheckBox chkbostoncake;
    private javax.swing.JCheckBox chkcappucino;
    private javax.swing.JCheckBox chkcoffeecake;
    private javax.swing.JCheckBox chkespresso;
    private javax.swing.JCheckBox chkicecappucino;
    private javax.swing.JCheckBox chkicelattle;
    private javax.swing.JCheckBox chklagoscake;
    private javax.swing.JCheckBox chklattle;
    private javax.swing.JCheckBox chkqueencake;
    private javax.swing.JCheckBox chkredcake;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea tareceipt;
    private javax.swing.JTextField txtbostoncake;
    private javax.swing.JTextField txtcappucino;
    private javax.swing.JTextField txtcoffecake;
    private javax.swing.JTextField txtcostofcake;
    private javax.swing.JTextField txtcostoftea;
    private javax.swing.JTextField txtespreeso;
    private javax.swing.JTextField txticecappucino;
    private javax.swing.JTextField txticelattle;
    private javax.swing.JTextField txtlagoscake;
    private javax.swing.JTextField txtlattle;
    private javax.swing.JTextField txtqueencake;
    private javax.swing.JTextField txtredcake;
    private javax.swing.JTextField txtservicecharges;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttax;
    public static javax.swing.JTextField txttotal;
    private javax.swing.JLabel txtuse;
    // End of variables declaration//GEN-END:variables
}
